---
- name: Installing firewall using host scope variables
  hosts: 172.31.18.113
  tasks: 
   - name: Install firewall
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
