---
- name: Configuring tomcat
  hosts: all
  tasks:
   - name: Install tomcat9
     apt:
      name: tomcat9
      state: present
   - name: Copt tomcat-users.xml
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: Change port from 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat9/server.xml
   - name: Restart tomcat9 service
     service:
      name: tomcat9
      state: restarted
   - name: url response from node1
     uri:
      url: http://3.129.43.244:9090
      status_code: 200
   - name: url response from node2
     uri:
      url: http://3.129.66.193:9090
      status_code: 200

...
